Individual Project/Razor Pages Web App/Pages/CreateSubmission.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Class_Library.Classes;
using Class_Library.DAL;
using Class_Library.Controllers;
using System.ComponentModel.DataAnnotations;

namespace Razor_Pages_Web_App.Pages
{
    public class CreateSubmissionModel : PageModel
    {
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public int Type {  get; set; }
        [BindProperty]
        public User User { get; set; }
        [BindProperty]
        public Game Game { get; set; }
		[BindProperty]
        [Required(ErrorMessage = "Date is required.")]
        public string DateInput { get; set; }
        [BindProperty]
        [Range(-1, 72, ErrorMessage = "Hours must be between 0 and 72.")]
        public int Hours {  get; set; }
        [BindProperty]
        [Range(-1, 59, ErrorMessage = "Minutes must be between 0 and 59.")]
        public int Minutes {  get; set; }
        [BindProperty]
        [Range(-1, 59, ErrorMessage = "Seconds must be between 0 and 59.")]
        public int Seconds { get; set; }
        [BindProperty]
        public int Platform { get; set; }
        [BindProperty]
        [Url(ErrorMessage = "Please enter a valid URL.")]
        public string Link { get; set; }
        [BindProperty]
        public bool TAS {  get; set; }
        [BindProperty]
        public bool Glitchless {  get; set; }
        [BindProperty]
        public bool AnyPercent {  get; set; }

        private GameController gameController = new(new GameDAL());
        private UserController userController = new(new UserDAL());
        private SubmissionController submissionController = new(new SubmissionDAL());
		public DateOnly Date
		{
			get
			{
				if (DateTime.TryParse(DateInput, out var dateTime))
				{
					return DateOnly.FromDateTime(dateTime);
				}
				return DateOnly.MinValue;
			}
		}
		public IActionResult OnGet(int id, int type)
        {
            try
            {
                Id = id;
                Type = type;

                string username = HttpContext.User.Identity.Name;

                ViewData["Message"] = username;

                User = userController.GetUserFromUsername(username);

                if (User.Banned == true)
                {
                    TempData["Message"] = "You cannot create submissions as you are banned at the moment.";
                    return RedirectToPage("./GameDetails", new { id = Id });
                }
                Game = gameController.ReadByID(Id);

                return Page();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"An error occurred: {ex.Message}");
                return Page();
            }        
        }
        public IActionResult OnPost(int id, int type)
        {
			try
			{
				Id = id;
				Type = type;

				string username = HttpContext.User.Identity.Name;
				ViewData["Message"] = username;

				User = userController.GetUserFromUsername(username);
				Game = gameController.ReadByID(id);

				if (User.Banned == true)
				{
					TempData["Message"] = "You cannot create submissions as you are banned at the moment.";
					return RedirectToPage("./GameDetails", new { id = Id });
				}

				if (DateTime.TryParse(DateInput, out var parsedDate))
				{
					if (parsedDate > DateTime.Now)
					{
						TempData["Message"] = "Please select a date that is not in the future.";
						return Page();
					}
				}
				else
				{
					TempData["Message"] = "Invalid date format.";
					return Page();
				}

                TimeSpan time = new TimeSpan(Hours, Minutes, Seconds);
                gameController.UpdateGameStats(Game, Hours, Minutes, Seconds);

                if (time.TotalSeconds <= 0)
				{
					TempData["Message"] = "Please enter a valid time for the speedrun.";
					return Page();
				}

				EnumPlatform platform = (EnumPlatform)Platform;

				if (Type == 1)
				{
					RankedSubmission submission = new(User, Game, DateOnly.FromDateTime(parsedDate), time, platform, Link);
					submissionController.Create(submission);
				}
				else
				{
					UnrankedSubmission submission = new(User, Game, DateOnly.FromDateTime(parsedDate), time, platform, TAS, Glitchless, AnyPercent);
					submissionController.Create(submission);
					UpdateGameStatistics(Game, time, User);
				}

				return RedirectToPage("./GameDetails", new { id = Id });
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("", $"An error occurred: {ex.Message}");
				return Page();
			}
		}

		private void UpdateGameStatistics(Game game, TimeSpan time, User user)
		{
			if (time < game.BestTime || game.BestTime == TimeSpan.Zero)
			{
				game.BestTime = time;
			}
			game.TotalTime = game.TotalTime.Add(time);
			game.NumberOfRuns++;
			if (!gameController.UserPlayedBefore(user, game))
			{
				game.NumberOfPlayers++;
			}
			gameController.Update(game);
		}
	}
}

Individual Project/Razor Pages Web App/Pages/Denied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor_Pages_Web_App.Pages
{
    public class DeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Individual Project/Razor Pages Web App/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Razor_Pages_Web_App.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Individual Project/Razor Pages Web App/Pages/GameDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Class_Library.DAL;
using Class_Library.Classes;
using Class_Library.Controllers;
namespace Razor_Pages_Web_App.Pages
{
	public class GameDetailsModel : PageModel
	{
		[BindProperty]
		public Game Game { get; set; }
		[BindProperty]
		public bool Banned { get; set; } = true;
		[BindProperty]
		public User User { get; set; }
		private GameController gameController = new(new GameDAL());
		private SubmissionController submissionController = new(new SubmissionDAL());
		private UserController userController = new(new UserDAL());
		[BindProperty]
		public RankedSubmission[] rankedSubmissions { get; set; }
		[BindProperty]
		public UnrankedSubmission[] unrankedSubmissions { get; set; }
		[BindProperty]
		public int Type { get; set; } = 1;
		public static int type = 1;
		[BindProperty]
		public int Id { get; set; }
		[BindProperty]
		public string Query { get; set; } = "";
		public static string query = "";
		public IActionResult OnGet(int id)
		{
			string username = HttpContext.User.Identity.Name;
			ViewData["Message"] = username;
			Id = id;
			Query = "";

			if (username != null)
			{
				User = userController.GetUserFromUsername(username);
				Banned = (bool)User.Banned;
			}
			Game = gameController.ReadByID(Id);

			if (Game == null)
			{
				TempData["Message"] = "Game does not exist.";
				return RedirectToPage("/Games");
			}

			if (Type == 1)
			{
				rankedSubmissions = submissionController.ReadRankedByGame(Id, Query);
			}
			else
			{
				unrankedSubmissions = submissionController.ReadByGame(Id, Query);
			}
			return Page();
		}

		public IActionResult OnPost(int id, int type, string query)
		{
			string username = HttpContext.User.Identity.Name;
			ViewData["Message"] = username;
			Id = id;
			Type = type;
			if (query == null)
			{
				Query = "";
			}
			else
			{
				Query = query;
			}

			if (username != null)
			{
				User = userController.GetUserFromUsername(username);
				Banned = (bool)User.Banned;
			}
			Game = gameController.ReadByID(Id);

			if (Game == null)
			{
				TempData["Message"] = "Game does not exist.";
				return RedirectToPage("/Games");
			}
			rankedSubmissions = submissionController.ReadRankedByGame(Id, Query);
			unrankedSubmissions = submissionController.ReadByGame(Id, Query);
			return Page();
		}
		public IActionResult OnPostClear(int id)
		{
			string username = HttpContext.User.Identity.Name;

			ViewData["Message"] = username;

			Id = id;
			Query = "";

			if (username != null)
			{
				User = userController.GetUserFromUsername(username);

				Banned = (bool)User.Banned;
			}
			Game = gameController.ReadByID(Id);

			if (Game == null)
			{
				TempData["Message"] = "Game does not exist!";
				return RedirectToPage("/Games");
			}

			if (Type == 1)
			{
				rankedSubmissions = submissionController.ReadRankedByGame(Id, Query);
			}
			else
			{
				unrankedSubmissions = submissionController.ReadByGame(Id, Query);
			}
			return Page();
		}
	}
}

Individual Project/Razor Pages Web App/Pages/Games.cshtml.cs
using Class_Library.Classes;
using Class_Library.DAL;
using Class_Library.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Razor_Pages_Web_App.Pages
{
    public class GamesModel : PageModel
    {
        [BindProperty]
        public Game[] GamePage { get; set; }
        public Game[] GameList { get; set; }
        private GameController gameController = new(new GameDAL());
        public int ID { get; private set; } = 0;
        public int Count { get; set; }
        public int pageSize = 8;
        [BindProperty]
        [StringLength(100, ErrorMessage = "Search query is too long.")]
        public string SearchQuery { get; set; }
        public int TotalPages { get; set; }
        public IActionResult OnGet(int id)
        {
            try
            {
                string username = HttpContext.User.Identity.Name;
                ViewData["Message"] = username;
                ID = id;
                GameList = gameController.ReadAllByName(SearchQuery);
                Count = GameList.Count();
                GamePage = gameController.ReadOnePageByName(ID, SearchQuery);
                TotalPages = gameController.GetTotalPages(Count);

                if (ID >= TotalPages)
                {
                    return RedirectToPage("/Games");
                }
                else
                {
                    return Page();
                }
            }
            catch (Exception ex) 
            {
                ViewData["ErrorMessage"] = $"Error occurred: {ex.Message}";
                return Page();
            }
            
        }
        public IActionResult OnPost(int id)
        {
            try
            {
                string username = HttpContext.User.Identity.Name;
                ViewData["Message"] = username;
                GameList = gameController.ReadAllByName(SearchQuery);
                Count = GameList.Count();
                GamePage = gameController.ReadOnePageByName(ID, SearchQuery);
                TotalPages = gameController.GetTotalPages(Count);

                if (ID >= TotalPages)
                {
                    return RedirectToPage("/Games");
                }
                else
                {
                    return Page();
                }
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"Error occurred: {ex.Message}";
                return Page();
            }         
        }
        public IActionResult OnPostClear()
        {
            try
            {
                string username = HttpContext.User.Identity.Name;
                ViewData["Message"] = username;
                return RedirectToPage("/Games");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"Error occurred: {ex.Message}";
                return Page();
            }   
        }
    }
}

Individual Project/Razor Pages Web App/Pages/Index.cshtml.cs
using Class_Library.Classes;
using Class_Library.Controllers;
using Class_Library.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor_Pages_Web_App.Pages
{	
	public class IndexModel : PageModel
	{
		private UserController userController = new(new UserDAL());
		private readonly ILogger<IndexModel> _logger;

		[BindProperty]
		public User LoggedUser { get; private set; }
		private SubmissionController submissionController = new(new SubmissionDAL());
		[BindProperty]
		public Submission[] submissions { get; set; }
		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			string username = HttpContext.User.Identity.Name;

			ViewData["Message"] = username;

			LoggedUser = userController.GetUserFromUsername(username);

			var allSubmissions = submissionController.ReadRecent("");
            submissions = allSubmissions.OrderByDescending(s => s.Date).Take(8).ToArray();
        }
	}
}

Individual Project/Razor Pages Web App/Pages/Profile.cshtml.cs
using Class_Library.Classes;
using Class_Library.Controllers;
using Class_Library.DAL;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Primitives;
using System.ComponentModel.DataAnnotations;

namespace Razor_Pages_Web_App.Pages
{
    public class ProfileModel : PageModel
    {       
        public ProfileModel(IWebHostEnvironment environment)
        {
            _environment = environment;
        }

        [BindProperty]
        public User LoggedUser { get; set; }

        [BindProperty]
        [Required]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please supply an email with at least 3 characters!")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        private UserController userController = new(new UserDAL());

        [BindProperty]
        [MaxLength(100, ErrorMessage = "Bio cannot be longer than 100 characters!")]
        public string Bio { get; set; }

        [BindProperty]
        public string UsernameColor { get; set; }

        public List<ProfileImage> PresetImages { get; private set; }

        private IWebHostEnvironment _environment;
        public string GetProfilePictureUrlById(int id)
        {
            return userController.GetProfilePictureUrlById(id);
        }
        public void OnGet()
        {
            string username = HttpContext.User.Identity.Name;
            ViewData["Message"] = username;

            LoggedUser = userController.GetUserFromUsername(username);
            PresetImages = userController.GetAllProfilePictures();

            if (PresetImages == null || !PresetImages.Any())
            {
                PresetImages = new List<ProfileImage>();
            }

            string profilePicUrl = userController.GetProfilePictureUrlById(LoggedUser.ProfilePicture);
            ViewData["ProfilePicUrl"] = profilePicUrl;
        }

        public IActionResult OnPost()
        {
            try
            {
                string username = HttpContext.User.Identity.Name;
                ViewData["Message"] = username;
                LoggedUser = userController.GetUserFromUsername(username);

                if (int.TryParse(Request.Form["SelectedProfileImage"], out int selectedImageId))
                {
                    LoggedUser.ProfilePicture = selectedImageId;
                }

                LoggedUser.Email = Email;
                LoggedUser.Bio = Bio;
                LoggedUser.UsernameColor = UsernameColor;

                userController.Update(LoggedUser);
                return RedirectToPage("/Profile");
            }
            catch (Exception ex)
            {
                ViewData["Error"] = "An error occurred while updating your profile: " + ex.Message;
                return Page();
            }
        }

        public IActionResult OnPostDelete()
        {
            try
            {
                string username = HttpContext.User.Identity.Name;
                ViewData["Message"] = username;
                LoggedUser = userController.GetUserFromUsername(username);

                userController.Delete(LoggedUser);
                HttpContext.SignOutAsync();

                return RedirectToPage("/Index");
            }
            catch (Exception ex)
            {
                ViewData["Error"] = "An error occurred while deleting your profile: " + ex.Message;
                return Page();
            }
        }
        public async Task<IActionResult> OnPostUpdateImageAsync(string image)
        {
            try
            {
                string username = HttpContext.User.Identity.Name;
                LoggedUser = userController.GetUserFromUsername(username);

                if (int.TryParse(image, out int profilePicId))
                {
                    LoggedUser.ProfilePicture = profilePicId;
                    bool updateResult = userController.Update(LoggedUser);

                    return new JsonResult(new { success = updateResult, message = updateResult ? "Profile picture updated successfully." : "Error updating profile picture." });
                }
                else
                {
                    return new JsonResult(new { success = false, message = "Error: Invalid image ID." });
                }
            }
            catch (Exception ex)
            {
                return new JsonResult(new { success = false, message = $"Error: {ex.Message}" });
            }
        }
    }
}

Individual Project/Razor Pages Web App/Pages/Denied.cshtml
@page
@model Razor_Pages_Web_App.Pages.DeniedModel
@{
    Layout = "_Layout";
}
<div class="container">
    <div class="text-center">
        <h3 class="text-danger display-4">Access Denied</h3>
        <h1 class="display-4">You do not have permission to access this page.</h1>
        <h1 class="display-4">Please log in or create an account to continue.</h1>
        <a asp-page="/Login" class="btn btn-primary">Log In</a>
        <a asp-page="/CreateAccount" class="btn btn-primary">Create Account</a>
    </div>
</div>

Individual Project/Razor Pages Web App/Pages/GameDetails.cshtml
@page
@using Class_Library.Classes;
@model Razor_Pages_Web_App.Pages.GameDetailsModel
@{
	ViewData["Title"] = @Model.Game.Name;
	Layout = "_Layout";
}

@if (TempData["Message"] != null)
{
	<div class="alert alert-danger centertext">
		@TempData["Message"]
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}

<body class="game-background" style="background-image: url('@Model.Game.BackgroundPictureLink');">

	<div class="grid-container">
		<div class="item-head">
			<h3>@Model.Game.Name (@Model.Game.ReleaseDate.Year)</h3>
			<h6>By @Model.Game.Company</h6>
			<h6>Platforms: @Model.Game.Platforms</h6>
			<h6>Genres: @Model.Game.Genres</h6>
			<h6><a href="@Model.Game.TrailerLink" class="link">Trailer link</a></h6>
		</div>
		<div class="item-stats">
			<h3>Stats</h3>
			<h6>Number of runs: @Model.Game.NumberOfRuns</h6>
			<h6>Number of players: @Model.Game.NumberOfPlayers</h6>
			<h6>Total time: @Model.Game.TotalTime.ToString() (estimate)</h6>
		</div>
		<div class="item-filter">
			<h4>Filter</h4>
			<form method="post">

				<label asp-for="@Model.Type">Speedrun type:</label>
				<select asp-for="@Model.Type" class="form-control mt-2">
					<option value="1">Ranked</option>
					<option value="2">Unranked</option>
				</select>

				<label asp-for="@Model.Query">Username:</label>
				<input type="text" asp-for="@Model.Query" value="@Model.Query" class="form-control mt-2" />

				<input type="submit" asp-page-handler="OnPost" asp-route-id="@Model.Game.ID" asp-route-type="@Model.Type" asp-route-query="@Model.Query" class="btn btn-light mt-2" value="Search" />
				<input type="submit" asp-page-handler="Clear" asp-route-id="@Model.Game.ID" class="btn btn-dark" value="Clear" />
			</form>
		</div>
		<div class="item-runs">

			@{
				if (Model.Type == 1)
				{
					if (Model.rankedSubmissions.Length > 0)
					{
						<div style="overflow-x:auto">
							<table class="leaderboard">
								<thead>
									<tr>
										<th>Rank</th>
										<th>Username</th>
										<th>Time</th>
										<th>Date</th>
										<th>Platform</th>
										<th>Link</th>
									</tr>
								</thead>
								<tbody>
									@foreach (RankedSubmission submission in Model.rankedSubmissions)
									{
										<tr>
											<td>@submission.Rank</td>
											<td><a class="profile" href="/UserProfile?id=@submission.User.Id"><span style="color:@submission.User.UsernameColor">@submission.User.Username</span></a></td>
											<td>@submission.TotalTime.ToString()</td>
											<td>@submission.Date</td>
											<td>@submission.Platform.ToString()</td>
											<td><a href="@submission.Link" class="link">Link</a></td>
										</tr>
									}
								</tbody>
							</table>
						</div>
					}

				}
				else
				{
					if (Model.unrankedSubmissions.Length > 0)
					{
						<div style="overflow-x:auto">
							<table class="leaderboard">
								<thead>
									<tr>
										<th>Username</th>
										<th>Time</th>
										<th>Date</th>
										<th>Platform</th>
										<th>TAS</th>
										<th>Glitchless</th>
										<th>Any%</th>
									</tr>
								</thead>
								<tbody>
									@foreach (UnrankedSubmission submission in Model.unrankedSubmissions)
									{
										<tr>
											<td><a class="profile" href="/UserProfile?id=@submission.User.Id"><span style="color:@submission.User.UsernameColor">@submission.User.Username</span></a></td>
											<td>@submission.TotalTime.ToString()</td>
											<td>@submission.Date</td>
											<td>@submission.Platform.ToString()</td>
											@{
												string tas;
												string glitch;
												string any;
												if (submission.TAS)
												{
													tas = "True";
												}
												else
												{
													tas = "False";
												}
												if (submission.Glitchless)
												{
													glitch = "True";
												}
												else
												{
													glitch = "False";
												}
												if (submission.AnyPercent)
												{
													any = "True";
												}
												else
												{
													any = "False";
												}
											}
											<td>@tas</td>
											<td>@glitch</td>
											<td>@any</td>
										</tr>
									}
								</tbody>
							</table>
						</div>
					}
				}
			}
		</div>
	</div>
	@if (Model.Banned == false)
	{
        <div class="bottom-right">
			<a asp-page="/CreateSubmission" asp-route-id="@Model.Game.ID" asp-route-type="1" class="btn btn-submission btn-ranked">
				Create Ranked Submission
			</a>

			<a asp-page="/CreateSubmission" asp-route-id="@Model.Game.ID" asp-route-type="0" class="btn btn-submission btn-unranked">
				Create Unranked Submission
			</a>
		</div>
	}
</body>

@section Scripts {
	<script>
		$(document).ready(function () {
			$('#showOverlayBtn').click(function () {
				$('#overlay').fadeIn();
			});

			$('.overlay').click(function () {
				$(this).fadeOut();
			});
		});
	</script>
}

Individual Project/Razor Pages Web App/Pages/Games.cshtml
@page
@model Razor_Pages_Web_App.Pages.GamesModel
@{
	ViewData["Title"] = "Games";
	Layout = "_Layout";
}

<h1>Games</h1>

<div class="text-center">
	<form method="post">
		<div class="input-group">
			<input type="text" asp-for="@Model.SearchQuery" class="form-control" placeholder ="Search games...">
			<input type="submit" asp-page-handler="OnPost" asp-route-id="0" class="btn btn-success" value="Search"/>
			<input type="submit" asp-page-handler="Clear" class="btn btn-outline-secondary" value="Clear" />
		</div>
	</form>
</div>
<br />

<div class="container">
	<div class="row">
		@foreach (var game in Model.GamePage)
		{
				<div class="col mb-3 mt-3">
					<div class="card centertext" style="width:300px; height:500px;">
						<div class="card-body">
							<img src="@game.PictureLink" style="width:250px; height:350px">
							<h5 class="card-title">@game.Name</h5>
						</div>
						<div class="card-footer" style="background-color:white; border:none">
							<a class="btn btn-secondary mb-3" asp-page="./GameDetails" asp-route-id="@game.ID">More details...</a>
						</div>
					</div>
				</div>
		}
	</div>
</div>

<nav aria-label="Game navigation">
	<ul class="pagination justify-content-center">
		@{
			int a = Model.ID - 1;
			if (a == -1)
			{
						<li class="page-item"><a class="btn btn-info disabled">Previous</a></li>
			}
			else
			{
						<li class="page-item"><a asp-page="/Games" asp-route-id="@a" class="page-link">Previous</a></li>
			}
		}
		@{
			for (int i = 0; i < Model.TotalPages; i++)
			{
				int j = i + 1;
				if (Model.ID == i)
				{
								<li class="page-item active"><a asp-page="/Games" asp-route-id="@i" class="page-link">@j</a></li>
				}
				else
				{
								<li class="page-item"><a asp-page="/Games" asp-route-id="@i" class="page-link">@j</a></li>
				}
			}
		}
		@{
			int b = Model.ID + 1;

			if (b == Model.TotalPages)
			{
						<li class="page-item"><a class="btn btn-info disabled">Next</a></li>
			}
			else
			{
						<li class="page-item"><a asp-page="/Games" asp-route-id="@b" class="page-link">Next</a></li>
			}
		}
	</ul>
</nav>

Individual Project/Razor Pages Web App/Pages/Logout.cshtml
@page
@model Razor_Pages_Web_App.Pages.LogoutModel
@{
}

Individual Project/Razor Pages Web App/Pages/MySubmissions.cshtml
@page
@using Class_Library.Classes;
@model Razor_Pages_Web_App.Pages.MySubmissionsModel
@{
}
<h1>Submissions</h1>

<<div class="container">
    <div class="row mb-3">
        <form method="post">
            <div class="input-group">

                <label asp-for="@Model.Type">Submission type:</label>
                <select asp-for="@Model.Type" class="form-control">
                    <option value="0" selected>All</option>
                    <option value="1">Ranked</option>
                    <option value="2">Unranked</option>
                </select>
                <input type="submit" asp-page-handler="OnPost" asp-route-type="@Model.Type" class="btn btn-primary" value="Search" />
                <input type="submit" asp-page-handler="Clear" class="btn btn-danger" value="Clear" />
            </div>
        </form>
    </div>
</div>

<div class="card">
    <table class="table table-striped table-bordered mt-4">
        <thead>
            <tr>
                <th>Game</th>
                <th>Platform</th>
                <th>Date</th>
                <th>Time</th>
                <th>More details</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model.submissions)
                {
                    <tr>
                        <td>@item.Game.Name</td>
                        <td>@item.Platform</td>
                        <td>@item.Date.ToShortDateString()</td>
                        <td>@item.TotalTime.ToString()</td>
                        @{
                            if (Model.subCont.ReadRanked(item.Id) != null)
                            {
                                RankedSubmission r = Model.subCont.ReadRanked(item.Id);
                                <td>
                                    <p>Rank: @r.Rank</p>
                                    <p><a href="@r.Link">Link</a></p>
                                    @{
                                        string status;
                                        if (@r.Approved == true)
                                        {
                                            status = "Approved";
                                        }
                                        else if (@r.Pending == true)
                                        {
                                            status = "Pending";
                                        }
                                        else
                                        {
                                            status = "Rejected";
                                        }
                                        <p>@status</p>
                                    }
                                </td>
                            }
                            else
                            {
                                <td>N/A</td>
                            }
                        }
                    </tr>
                }
            }
        </tbody>
    </table>

</div>